"""
Usage: Python or python3 2dplot.py <file1.csv> [file2.csv ...]
"""
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from matplotlib.patches import Patch
import numpy as np
import sys
from pathlib import Path
from scipy.interpolate import griddata
import rasterio

def filter_percentiles(view, percentiles):
    """
    Clamps values between the specified percentiles to remove extreme outliers.
    """
    # Calculate the percentile limits (ignoring NaNs if any exist)
    lims = np.nanpercentile(view, percentiles)
    
    # Clamp values
    filtered_view = np.where(view < lims[0], lims[0], view)
    filtered_view = np.where(filtered_view > lims[1], lims[1], filtered_view)
    return filtered_view

def create_2dplot_cbd_tif(tif_path):
    print(f"Loading raster data from: {tif_path}")
    
    with rasterio.open(tif_path) as src:
        # Check available bands/names
        # fCBDprofile_fuelmetrics returns a raster with many bands.
        # We need to find 'CBD_max'. 
        
        # Typically descriptors might be available if using recent GDAL/rasterio
        # If not, we rely on the layers order or standard naming if generated by terra
        descriptions = src.descriptions
        
        target_band_idx = None
        
        if descriptions and any(descriptions):
            for idx, desc in enumerate(descriptions):
                if desc and 'CBD_max' in desc:
                    target_band_idx = idx + 1
                    break
        
        # If not found by name, fallback to a likely index or warn
        # Assuming index 2 or 3 might be safe, but typically we want confirmation.
        # Let's try to list them
        print(f"  Bands found: {len(descriptions) if descriptions else src.count}")
        # print(f"  Descriptions: {descriptions}")
        
        if target_band_idx is None:
            # Fallback for now: Check if we can find it by typical name if descriptions are empty
            # Or ask user? For now, let's assume if it was generated by our previous script
            # we might need to rely on the fact that fCBDprofile_fuelmetrics usually puts it at a certain spot
            # or try to match names if available.
            
            # If standard naming fails, let's assume it's one of the bands by index? 
            # In the previous script logic "metrics_r" returned by pixel_metrics had names.
            # Let's assume description matches. If not, we default to band 1 but print warning.
            
            # Additional logic: Check if we can read associated .aux.xml if widely supported
            # But let's try to search blindly for "CBD" substring
            for idx, desc in enumerate(descriptions):
                if desc and "CBD" in desc and "max" in desc:
                     target_band_idx = idx + 1
                     break
            
            if target_band_idx is None:
                # Try finding just 'CBD' if it's a single layer or max is implied
                 for idx, desc in enumerate(descriptions):
                    if desc and "CBD" in desc:
                         target_band_idx = idx + 1
                         break
            
            if target_band_idx is None:
                print("  Warning: 'CBD_max' band not explicitly identified. Plotting Band 1.")
                target_band_idx = 1
        
        print(f"  Plotting Band {target_band_idx} ({descriptions[target_band_idx-1] if descriptions else 'Unknown'})")
        
        # Read the data
        cbd_data = src.read(target_band_idx)
        
        # Handle NoData
        nodata = src.nodata
        if nodata is not None:
             cbd_data = np.where(cbd_data == nodata, np.nan, cbd_data)
             
        # Convert R's -1 or negative values to 0 filter logic if needed
        # In the pipeline, we used NA for -1, so it should be NaN or NodATA
        # But if it wasn't substituted, we clean it here
        cbd_data[cbd_data < 0] = np.nan
        
        # Flip? Rasterio reads as array (Row, Col). 
        # imshow with origin='lower' expects index [0,0] to be bottom-left
        # GeoTiff convention: [0,0] is Top-Left. 
        # So we do NOT need to flip if we use extent properly, or we flip UD if we want simple visual
        # Let's use simple matrix plot
        
        # Note: 2dplot_cbd usually plots Transpose? 
        # create_2dplot_cbd did: grid_cbd_t = grid_cbd.T
        # Let's stick to standard raster plotting conventions: 
        # Array shape (H, W). Plotting with extent should handle it.
        
        transform = src.transform
        width = src.width
        height = src.height
        
        # Calculate extent
        left = transform[2]
        top = transform[5]
        right = left + (width * transform[0])
        bottom = top + (height * transform[4])
        
        plot_extent = [left, right, bottom, top]

        # 6. Apply Percentile Filter
        print("  Applying percentile filter [2, 98]...")
        # Replace NaNs with 0 for visualization or ignore
        cbd_clean = np.nan_to_num(cbd_data, 0)
        # Filter (robust against outliers)
        cbd_filtered = filter_percentiles(cbd_clean, [2, 98])
        
        # 7. Visualization logic similar to csv function
        colors = ["darkblue","darkgreen", "green", "yellow", "orange","red","darkred","brown"]
        cmap = mcolors.LinearSegmentedColormap.from_list("fire_risk", colors)
        norm = plt.Normalize(vmin=0.0, vmax=0.10)
        
        fig, ax = plt.subplots(figsize=(12, 10))
        
        # Rasterio array is (Row, Col) = (Y, X) usually.
        # imshow displays [0,0] at top-left by default. 
        # GeoTransform usually implies y decreases.
        
        img = ax.imshow(cbd_filtered, extent=plot_extent, cmap=cmap, norm=norm)
        
        cbar = plt.colorbar(img, ax=ax)
        cbar.set_label('Canopy Bulk Density (kg/m³)')
        
        legend_elements = [
            Patch(facecolor='darkblue', edgecolor='black', label='~0.00: No Canopy / Gap'),
            Patch(facecolor='green', edgecolor='black', label='< 0.04: Low Density'),
            Patch(facecolor='yellow', edgecolor='black', label='0.04 - 0.06: Moderate'),
            Patch(facecolor='red', edgecolor='black', label='> 0.08: High Density')
        ]
        
        ax.legend(handles=legend_elements, loc='upper right', title="Density Levels")
        
        ax.set_title(f"2D Fuel Density Map (From TIF)\nFile: {Path(tif_path).name}")
        ax.set_xlabel('Easting')
        ax.set_ylabel('Northing')
        ax.set_aspect('equal')
        ax.grid(True, alpha=0.3)
        
        plt.tight_layout()
        
        results_dir = Path('results')
        plots_dir = results_dir / 'plots'
        plots_dir.mkdir(parents=True, exist_ok=True)
        
        stem = Path(tif_path).stem
        output_file = plots_dir / f"{stem}_2d_plot.png"
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        print(f"Saved plot to: {output_file}\n")


def create_2dplot_cbd(csv_path):
    print(f"Loading data from: {csv_path}")
    
    df = pd.read_csv(csv_path)
    df.columns = df.columns.str.strip()
    
    # 1. Identify Height Column
    height_col = 'H' 
    if height_col not in df.columns and 'Height' in df.columns:
        height_col = 'Height'
        
    required_cols = ['X', 'Y', 'CBD', height_col]
    
    # 2. Filter Clean Data
    df_clean = df.dropna(subset=required_cols)
    
    if df_clean.empty:
        print("  Error: No valid data points found.")
        return

    points = df_clean[['X', 'Y']].values
    values_cbd = df_clean['CBD'].values
    values_height = df_clean[height_col].values
    
    print(f"Processing {len(values_cbd)} points...")

    # 3. Define Grid (Resolution = 1.0m)
    resolution = 1.0
    x_min, x_max = np.min(points[:,0]), np.max(points[:,0])
    y_min, y_max = np.min(points[:,1]), np.max(points[:,1])
    
    grid_x, grid_y = np.mgrid[
        x_min:x_max:resolution, 
        y_min:y_max:resolution
    ]
    
    print("  Interpolating grids...")
    

    grid_cbd = griddata(points, values_cbd, (grid_x, grid_y), method='linear')
    grid_height = griddata(points, values_height, (grid_x, grid_y), method='linear')

    mask_nan_cbd = np.isnan(grid_cbd)
    if np.any(mask_nan_cbd):
        grid_cbd[mask_nan_cbd] = griddata(points, values_cbd, (grid_x[mask_nan_cbd], grid_y[mask_nan_cbd]), method='nearest')
        
    mask_nan_h = np.isnan(grid_height)
    if np.any(mask_nan_h):
        grid_height[mask_nan_h] = griddata(points, values_height, (grid_x[mask_nan_h], grid_y[mask_nan_h]), method='nearest')

    # 5. Apply Height Threshold
    height_threshold = 1
    print(f"  Filtering low vegetation (Height <= {height_threshold}m)...")
    grid_cbd[grid_height <= height_threshold] = 0

    # 6. Apply Percentile Filter
    print("  Applying percentile filter [2, 98]...")
    grid_cbd = filter_percentiles(grid_cbd, [2, 98])


    grid_cbd_t = grid_cbd.T
    
    # Define Plot Extents
    x_center = (x_min + x_max) / 2
    y_center = (y_min + y_max) / 2
    plot_extent = [x_min - x_center, x_max - x_center, y_min - y_center, y_max - y_center]
    
    # 7. Visualization
    colors = ["darkblue","darkgreen", "green", "yellow", "orange","red","darkred","brown"]
    cmap = mcolors.LinearSegmentedColormap.from_list("fire_risk", colors)

    

    norm = plt.Normalize(vmin=0.0, vmax=0.10)
    
    fig, ax = plt.subplots(figsize=(12, 10))
    
    img = ax.imshow(grid_cbd_t, extent=plot_extent, origin='lower', cmap=cmap, norm=norm)
    
    cbar = plt.colorbar(img, ax=ax)
    cbar.set_label('Canopy Bulk Density (kg/m³)')
    

    legend_elements = [
        Patch(facecolor='darkblue', edgecolor='black', label='~0.00: No Canopy / Gap'),
        Patch(facecolor='green', edgecolor='black', label='< 0.04: Low Density'),
        Patch(facecolor='yellow', edgecolor='black', label='0.04 - 0.06: Moderate'),
        Patch(facecolor='red', edgecolor='black', label='> 0.08: High Density')
    ]
    
    ax.legend(handles=legend_elements, loc='upper right', title="Density Levels")
    
    ax.set_title(f"2D Fuel Density Map\n(Interpolation: Linear+Nearest | Filter: Percentile [2,98])")
    ax.set_xlabel('X (meters from center)')
    ax.set_ylabel('Y (meters from center)')
    ax.set_aspect('equal')
    ax.grid(True, alpha=0.3)
    
    plt.tight_layout()
    
    results_dir = Path('results')
    plots_dir = results_dir / 'plots'
    plots_dir.mkdir(parents=True, exist_ok=True)
    
    stem = Path(csv_path).stem
    output_file = plots_dir / f"{stem}_2d_plot.png"
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"Saved plot to: {output_file}\n")


if __name__ == "__main__":
    if len(sys.argv) > 1:
        files = sys.argv[1:]
    else:
        print("No files provided. Searching for *_profile.csv and *.tif in results/...")
        results_dir = Path('results')
        files = []
        if results_dir.exists():
            files.extend(list(results_dir.glob('*_fuel_metrics.tif')))
            
            if not files:
                print("No suitable files found in results/.")
        else:
            print("Results directory not found.")

    for f in files:
        f_path = str(f)
        if f_path.endswith('.tif'):
            try:
                create_2dplot_cbd_tif(f_path)
            except Exception as e:
                print(f"Error plotting TIF {f_path}: {e}")
        elif f_path.endswith('.csv'):
            create_2dplot_cbd(f_path)